### ISSUE TITLE
auth0 broken

### ISSUE THREAD

**Issue by kaspar030** [cogentapps/chat-with-gpt#159]
I recently pulled the latest container, and suddenly my auth0 authentication (against authelia) doesn't work anymore.
chat-with-gpt correctly forwards to the login prompt (e.g., when clicking on "sign in to sync"), but when back, the app is not signed in.

The logs contain this:

```
chat-with-gpt-chat-with-gpt-1  | TypeError: request.isAuthenticated is not a function
chat-with-gpt-chat-with-gpt-1  |     at /app/src/endpoints/session.ts:14:61
chat-with-gpt-chat-with-gpt-1  |     at Array.filter (<anonymous>)
chat-with-gpt-chat-with-gpt-1  |     at SessionRequestHandler.<anonymous> (/app/src/endpoints/session.ts:10:14)
chat-with-gpt-chat-with-gpt-1  |     at Generator.next (<anonymous>)
chat-with-gpt-chat-with-gpt-1  |     at /app/src/endpoints/session.ts:8:71
chat-with-gpt-chat-with-gpt-1  |     at new Promise (<anonymous>)
chat-with-gpt-chat-with-gpt-1  |     at __awaiter (/app/src/endpoints/session.ts:4:12)
chat-with-gpt-chat-with-gpt-1  |     at SessionRequestHandler.handler (/app/src/endpoints/session.ts:20:16)
chat-with-gpt-chat-with-gpt-1  |     at SessionRequestHandler.<anonymous> (/app/src/endpoints/base.ts:26:31)
chat-with-gpt-chat-with-gpt-1  |     at Generator.next (<anonymous>)

**Comment by cogentapps** [comment]
Should be fixed now, would you be able to check again?

**Comment by kaspar030** [comment]
> Should be fixed now, would you be able to check again?

Seems fixed. Thanks a lot. That was fast!
