### ISSUE TITLE
error TS2339: Property 'value' does not exist on type '{}'.

### ISSUE THREAD

**Issue by fjiasigmoid** [cogentapps/chat-with-gpt#23]
Hi! UI looks great. Was trying to do docker-compose up and got this error when attempting to run the container.  Can you please advise? Thanks!

System:  mac m1 pro; OS: Ventura 13.1

Full error message: 
```
Attaching to chat-with-gpt-app-1
chat-with-gpt-app-1  |
chat-with-gpt-app-1  | > Chat with GPT Server@0.2.0 start
chat-with-gpt-app-1  | > npx ts-node src/index.ts
chat-with-gpt-app-1  |
chat-with-gpt-app-1  | /app/node_modules/ts-node/src/index.ts:859
chat-with-gpt-app-1  |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
chat-with-gpt-app-1  |            ^
chat-with-gpt-app-1  | TSError: ⨯ Unable to compile TypeScript:
chat-with-gpt-app-1  | src/object-store/sqlite.ts(29,34): error TS2339: Property 'value' does not exist on type '{}'.
chat-with-gpt-app-1  |
chat-with-gpt-app-1  |     at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
chat-with-gpt-app-1  |     at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
chat-with-gpt-app-1  |     at getOutput (/app/node_modules/ts-node/src/index.ts:1077:36)
chat-with-gpt-app-1  |     at Object.compile (/app/node_modules/ts-node/src/index.ts:1433:41)
chat-with-gpt-app-1  |     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1617:30)
chat-with-gpt-app-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
chat-with-gpt-app-1  |     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
chat-with-gpt-app-1  |     at Module.load (node:internal/modules/cjs/loader:1069:32)
chat-with-gpt-app-1  |     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
chat-with-gpt-app-1  |     at Module.require (node:internal/modules/cjs/loader:1093:19) {
chat-with-gpt-app-1  |   diagnosticCodes: [ 2339 ]
chat-with-gpt-app-1  | }
chat-with-gpt-app-1 exited with code 1
```

**Comment by bdfrost** [comment]
The same exact issue on the same OS and processor (System: mac m1 pro; OS: Ventura 13.1)

**Comment by cogentapps** [comment]
Fixed:

git pull
docker-compose up —build

to rebuild your docker containers.

I’ve added a Github Action job to catch errors like this in the future.
