### ISSUE TITLE
Unable to create account/login

### ISSUE THREAD

**Issue by iribarrenjg** [cogentapps/chat-with-gpt#42]
Hello, 

Thanks for the project. 

When creating an account and sometimes when login the server crashes and I can see the following on the console:

2023-03-17 12:30:50 /app/src/database/sqlite.ts:92
2023-03-17 12:30:50                         passwordHash: Buffer.from(row.password_hash),
2023-03-17 12:30:50                                                       ^
2023-03-17 12:30:50 TypeError: Cannot read properties of undefined (reading 'password_hash')
2023-03-17 12:30:50     at Statement.<anonymous> (/app/src/database/sqlite.ts:92:55)
2023-03-17 12:30:50     at Statement.replacement (/app/node_modules/sqlite3/lib/trace.js:25:27)
2023-03-17 12:30:50     at Statement.replacement (/app/node_modules/sqlite3/lib/trace.js:25:27)

On the browser it just shows "empty response".

It is hosted using docker and this has been tested on two completely different machines (hosted on two different machines and different networks). 

Also tested on Edge & Chrome & Firefox.

If you need any other details please let me know.

**Comment by cogentapps** [comment]
The error is a bug that happens when you sign into a non-existent account. That bug is fixed now (docker pull to update). However, for the account to not exist, something must have gone wrong when you created an account too. Do you see any other errors on sign up specifically?

**Comment by iribarrenjg** [comment]
I was going to try but after the pull (and tested on a different machine from scratch) it just keeps loading: 

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/22754062/226129931-2d229284-424f-41f6-a12b-cbc0ee4def42.png">

**Comment by cogentapps** [comment]
New update from today rolls back a change to the security config that seemed to be causing problems for users and may be related to your issue. Can you try again and see if the issue is resolved? Otherwise I'll take a deeper look and try to reproduce those errors.

**Comment by iribarrenjg** [comment]
[Resolved]
